services:
  dns:
    image: andyshinn/dnsmasq:latest
    container_name: dnsmasq
    networks:
      rete1:
        ipv4_address: 192.168.2.10
      rete2:
        ipv4_address: 192.168.3.10
    command: >
      --domain=rete1
      --domain=rete2
      --addn-hosts=/etc/dnsmasq.hosts
      --expand-hosts
      --domain-needed
      --no-resolv
      --no-hosts
      --log-queries
      --server=8.8.8.8
      --server=8.8.4.4
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq.hosts:/etc/dnsmasq.hosts

  router:
    image: ubuntu:latest
    container_name: router1
    privileged: true
    stdin_open: true
    tty: true
    networks:
      rete1:
        ipv4_address: 192.168.2.2
      rete2:
        ipv4_address: 192.168.3.2
    dns:
      - 192.168.2.10
    command: >
      /bin/bash -c "apt-get update &&
                    apt-get install -y iputils-ping iproute2 dnsutils nano  &&
                    sysctl -w net.ipv4.ip_forward=1 &&
                    ip route replace 192.168.3.0/28 via 192.168.3.2 &&
                    ip route replace 192.168.2.0/28 via 192.168.2.2 &&
                    /bin/bash"

  pc1:
    image: ubuntu:latest
    container_name: pc1
    privileged: true
    stdin_open: true
    tty: true
    networks:
      rete1:
        ipv4_address: 192.168.2.3
    dns:
      - 192.168.2.10
    depends_on:
      - dns
      - router
    command: >
      /bin/bash -c "apt-get update &&
                    apt-get install -y iputils-ping iproute2 dnsutils nano  &&
                    ip route replace default via 192.168.2.2 &&
                    /bin/bash"

  pc2:
    image: ubuntu:latest
    container_name: pc2
    privileged: true
    stdin_open: true
    tty: true
    networks:
      rete1:
        ipv4_address: 192.168.2.4
    dns:
      - 192.168.2.10
    depends_on:
      - dns
      - router
    command: >
      /bin/bash -c "apt-get update &&
                    apt-get install -y iputils-ping iproute2 dnsutils nano  &&
                    ip route replace default via 192.168.2.2 &&
                    /bin/bash"

  pc3:
    image: ubuntu:latest
    container_name: pc3
    privileged: true
    stdin_open: true
    tty: true
    networks:
      rete2:
        ipv4_address: 192.168.3.3
    dns:
      - 192.168.3.10
    depends_on:
      - dns
      - router
    command: >
      /bin/bash -c "apt-get update &&
                    apt-get install -y iputils-ping iproute2 dnsutils nano  &&
                    ip route replace default via 192.168.3.2 &&
                    /bin/bash"

networks:
  rete1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/28
          gateway: 192.168.2.1

  rete2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.3.0/28
          gateway: 192.168.3.1