services:
  dns:
    image: andyshinn/dnsmasq:latest
    container_name: dnsmasq
    networks:
      lan_20:
        ipv4_address: 192.168.20.10
      lan_30:
        ipv4_address: 192.168.30.10
      lan_40:
        ipv4_address: 192.168.40.10
      lan_50:
        ipv4_address: 192.168.50.10
    command: >
      --domain=lan_20
      --domain=lan_30
      --domain=lan_40
      --domain=lan_50
      --addn-hosts=/etc/dnsmasq.hosts
      --expand-hosts
      --domain-needed
      --no-resolv
      --no-hosts
      --log-queries
      --server=8.8.8.8
      --server=8.8.4.4
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq.hosts:/etc/dnsmasq.hosts

  router1:
    image: ubuntu:24.04
    container_name: router1
    privileged: true
    stdin_open: true
    tty: true
    networks:
      lan_20:
        ipv4_address: 192.168.20.2
      lan_30:
        ipv4_address: 192.168.30.2
      transit:
        ipv4_address: 192.168.100.2
    dns:
      - 192.168.20.10
    depends_on:
      - dns
    command: >
      /bin/bash -c "apt-get update &&
                    apt-get install -y iputils-ping iproute2 traceroute iputils-tracepath dnsutils curl wget nano &&
                    sysctl -w net.ipv4.ip_forward=1 &&
                    ip route add 192.168.40.0/28 via 192.168.100.3 &&
                    ip route add 192.168.50.0/28 via 192.168.100.3 &&
                    /bin/bash"

  router2:
    image: ubuntu:24.04
    container_name: router2
    privileged: true
    stdin_open: true
    tty: true
    networks:
      lan_40:
        ipv4_address: 192.168.40.2
      lan_50:
        ipv4_address: 192.168.50.2
      transit:
        ipv4_address: 192.168.100.3
    dns:
      - 192.168.40.10
    depends_on:
      - dns
    command: >
      /bin/bash -c "apt-get update &&
                    apt-get install -y iputils-ping iproute2 traceroute iputils-tracepath dnsutils curl wget nano &&
                    sysctl -w net.ipv4.ip_forward=1 &&
                    ip route add 192.168.20.0/28 via 192.168.100.2 &&
                    ip route add 192.168.30.0/28 via 192.168.100.2 &&
                    /bin/bash"


  pc1:
    image: ubuntu:24.04
    container_name: pc1
    privileged: true
    stdin_open: true
    tty: true
    networks:
      lan_20:
        ipv4_address: 192.168.20.3
    dns:
      - 192.168.20.10
    depends_on:
      - dns
      - router1
    command: >
      /bin/bash -c "apt-get update &&
                    apt-get install -y iputils-ping iproute2 traceroute iputils-tracepath dnsutils curl wget nano  &&
                    ip route replace default via 192.168.20.2 &&
                    /bin/bash"

  pc2:
    image: ubuntu:24.04
    container_name: pc2
    privileged: true
    stdin_open: true
    tty: true
    networks:
      lan_20:
        ipv4_address: 192.168.20.4
    dns:
      - 192.168.20.10
    depends_on:
      - dns
      - router1
    command: >
      /bin/bash -c "apt-get update &&
                    apt-get install -y iputils-ping iproute2 traceroute iputils-tracepath dnsutils curl wget nano  &&
                    ip route replace default via 192.168.20.2 &&
                    /bin/bash"

  pc3:
    image: ubuntu:24.04
    container_name: pc3
    privileged: true
    stdin_open: true
    tty: true
    networks:
      lan_30:
        ipv4_address: 192.168.30.3
    dns:
      - 192.168.30.10
    depends_on:
      - dns
      - router1
    command: >
      /bin/bash -c "apt-get update &&
                    apt-get install -y iputils-ping iproute2 traceroute iputils-tracepath dnsutils curl wget nano  &&
                    ip route replace default via 192.168.30.2 &&
                    /bin/bash"

  pc4:
    image: ubuntu:24.04
    container_name: pc4
    privileged: true
    stdin_open: true
    tty: true
    networks:
      lan_40:
        ipv4_address: 192.168.40.3
    dns:
      - 192.168.40.10
    depends_on:
      - dns
      - router2
    command: >
      /bin/bash -c "apt-get update &&
                    apt-get install -y iputils-ping iproute2 traceroute iputils-tracepath dnsutils curl wget nano  &&
                    ip route replace default via 192.168.40.2 &&
                    /bin/bash"

  pc5:
    image: ubuntu:24.04
    container_name: pc5
    privileged: true
    stdin_open: true
    tty: true
    networks:
      lan_40:
        ipv4_address: 192.168.40.4
    dns:
      - 192.168.40.10
    depends_on:
      - dns
      - router2
    command: >
      /bin/bash -c "apt-get update &&
                    apt-get install -y iputils-ping iproute2 traceroute iputils-tracepath dnsutils curl wget nano  &&
                    ip route replace default via 192.168.40.2 &&
                    /bin/bash"
  # server_web:
  #   image: nginx:latest
  #   container_name: server_web
  #   networks:
  #     lan_40:
  #       ipv4_address: 192.168.40.5
  #   dns:
  #     - 192.168.40.10
  #   depends_on:
  #     - dns
  #     - router2
  #   ports:
  #     - "80:80"  # Espone la porta 80 del server web all'host
  #   command: >
  #     /bin/bash -c "ip route replace default via 192.168.40.2 && nginx -g 'daemon off;'"

networks:
  lan_20:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/28
          gateway: 192.168.20.1

  lan_30:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.30.0/28
          gateway: 192.168.30.1

  lan_40:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.40.0/28
          gateway: 192.168.40.1

  lan_50:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.50.0/28
          gateway: 192.168.50.1

  transit:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/29
          gateway: 192.168.100.1