services:
  dns:
    image: andyshinn/dnsmasq:latest
    container_name: dnsmasq
    networks:
      lan_20:
        ipv4_address: 192.168.20.10
      lan_30:
        ipv4_address: 192.168.30.10
      lan_40:
        ipv4_address: 192.168.40.10
      lan_60:
        ipv4_address: 192.168.60.10
    command: >
      --domain=lan_20
      --domain=lan_30
      --domain=lan_40
      --domain=lan_60
      --addn-hosts=/etc/dnsmasq.hosts
      --expand-hosts
      --domain-needed
      --no-resolv
      --no-hosts
      --log-queries
      --server=8.8.8.8
      --server=8.8.4.4
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq.hosts:/etc/dnsmasq.hosts

  router1:
    image: manzolo/ubuntu-network-playground-router
    container_name: router1
    privileged: true
    stdin_open: true
    tty: true
    networks:
      lan_20:
        ipv4_address: 192.168.20.2
      lan_30:
        ipv4_address: 192.168.30.2
      transit_12:
        ipv4_address: 192.168.100.2
    dns:
      - 192.168.20.10
    depends_on:
      - dns
    volumes:
      - ./scripts/router-setup.sh:/scripts/router-setup.sh
    environment:
      - ROUTES=192.168.40.0/28 via 192.168.100.3,192.168.60.0/28 via 192.168.100.3
    command: /scripts/router-setup.sh

  router2:
    image: manzolo/ubuntu-network-playground-router
    container_name: router2
    privileged: true
    stdin_open: true
    tty: true
    networks:
      lan_40:
        ipv4_address: 192.168.40.2
      transit_12:
        ipv4_address: 192.168.100.3
      transit_23:
        ipv4_address: 192.168.200.2
    dns:
      - 192.168.40.10
    depends_on:
      - dns
    volumes:
      - ./scripts/router-setup.sh:/scripts/router-setup.sh
    environment:
      - ROUTES=192.168.20.0/28 via 192.168.100.2,192.168.30.0/28 via 192.168.100.2,192.168.60.0/28 via 192.168.200.3
    command: /scripts/router-setup.sh

  router3:
    image: manzolo/ubuntu-network-playground-router
    container_name: router3
    privileged: true
    stdin_open: true
    tty: true
    networks:
      lan_60:
        ipv4_address: 192.168.60.2
      transit_23:
        ipv4_address: 192.168.200.3
    dns:
      - 192.168.60.10
    depends_on:
      - dns
    volumes:
      - ./scripts/router-setup.sh:/scripts/router-setup.sh
    environment:
      - ROUTES=192.168.20.0/28 via 192.168.200.2,192.168.30.0/28 via 192.168.200.2,192.168.40.0/28 via 192.168.200.2
    command: /scripts/router-setup.sh

  pc1:
    image: manzolo/ubuntu-network-playground-pc
    container_name: pc1
    privileged: true
    stdin_open: true
    tty: true
    networks:
      lan_20:
        ipv4_address: 192.168.20.3
    dns:
      - 192.168.20.10
    depends_on:
      - dns
      - router1
    volumes:
      - ./scripts/pc-setup.sh:/scripts/pc-setup.sh
    environment:
      - ROUTES=default via 192.168.20.2
    command: /scripts/pc-setup.sh

  pc2:
    image: manzolo/ubuntu-network-playground-pc
    container_name: pc2
    privileged: true
    stdin_open: true
    tty: true
    networks:
      lan_20:
        ipv4_address: 192.168.20.4
    dns:
      - 192.168.20.10
    depends_on:
      - dns
      - router1
    volumes:
      - ./scripts/pc-setup.sh:/scripts/pc-setup.sh
    environment:
      - ROUTES=default via 192.168.20.2
    command: /scripts/pc-setup.sh

  pc3:
    image: manzolo/ubuntu-network-playground-pc
    container_name: pc3
    privileged: true
    stdin_open: true
    tty: true
    networks:
      lan_30:
        ipv4_address: 192.168.30.3
    dns:
      - 192.168.30.10
    depends_on:
      - dns
      - router1
    volumes:
      - ./scripts/pc-setup.sh:/scripts/pc-setup.sh
    environment:
      - ROUTES=default via 192.168.30.2
    command: /scripts/pc-setup.sh

  pc4:
    image: manzolo/ubuntu-network-playground-pc
    container_name: pc4
    privileged: true
    stdin_open: true
    tty: true
    networks:
      lan_40:
        ipv4_address: 192.168.40.3
    dns:
      - 192.168.40.10
    depends_on:
      - dns
      - router2
    volumes:
      - ./scripts/pc-setup.sh:/scripts/pc-setup.sh
    environment:
      - ROUTES=default via 192.168.40.2
    command: /scripts/pc-setup.sh

  pc5:
    image: manzolo/ubuntu-network-playground-pc
    container_name: pc5
    privileged: true
    stdin_open: true
    tty: true
    networks:
      lan_40:
        ipv4_address: 192.168.40.4
    dns:
      - 192.168.40.10
    depends_on:
      - dns
      - router2
    volumes:
      - ./scripts/pc-setup.sh:/scripts/pc-setup.sh
    environment:
      - ROUTES=default via 192.168.40.2
    command: /scripts/pc-setup.sh

  server_web:
    image: manzolo/ubuntu-network-playground-webserver
    container_name: server_web
    privileged: true
    networks:
      lan_60:
        ipv4_address: 192.168.60.5
    dns:
      - 192.168.60.10
    depends_on:
      - dns
      - router3
    ports:
      - "80:80"  # Espone la porta 80 del server web all'host
    volumes:
      - ./scripts/web-setup.sh:/scripts/web-setup.sh
    environment:
      - ROUTES=default via 192.168.60.2
    command: /scripts/web-setup.sh

networks:
  lan_20:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/28
          gateway: 192.168.20.1

  lan_30:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.30.0/28
          gateway: 192.168.30.1

  lan_40:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.40.0/28
          gateway: 192.168.40.1

  lan_60:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.60.0/28
          gateway: 192.168.60.1

  transit_12:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/29
          gateway: 192.168.100.1

  transit_23:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/29
          gateway: 192.168.200.1